#!/usr/bin/env python3

#    /usr/bin/bld
#    Sat Dec  7 21:18:22 UTC 2024

#    The entry-point to the front end of the builds source building system
#
#    Copyright:: (c) 2024
#    Author:: Darren Kirby (mailto:bulliver@gmail.com)

#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import sys
import os


def get_builds_path() -> [None, str]:
    """
    Read the configuration file and return script location
    so that it can be added to sys.path.
    """
    if os.getuid() == 0:
        # System-wide configuration
        config_file = "/etc/builds.conf"
    else:
        # User-specific configuration
        config_file = os.path.expanduser("~/.config/builds/builds.conf")

    # Check if the configuration file exists
    if not os.path.isfile(config_file):
        print(f"Cannot find configuration file: {config_file}")
        sys.exit(2)

    with open(config_file, "r") as f:
        config = {}
        for line in f:
            if "=" in line:
                key, value = line.strip().split("=", 1)
                config[key.strip()] = value.strip()

        # Get builds_root and construct scripts path
        builds_root = config.get("builds_root")
        if builds_root:
            return os.path.join(builds_root, "scripts")

    return None


# Determine the builds scripts path
builds_path = get_builds_path()
if builds_path and os.path.isdir(builds_path):
    sys.path.insert(0, builds_path)
else:
    print("Error: Could not locate builds scripts path.")
    sys.exit(1)

import builds
import common_functions as cf

try:
    builds.do_main()
except KeyboardInterrupt:
    print()
    cf.red("keyboard interupt received...")
    cf.red("temporary build files possibly left on filesystem")
    sys.exit(-1)
