#!/usr/bin/env python3

#    /usr/sbin/bld
#    Sun Oct 19 03:34:12 UTC 2014

#    The front end to the builds source building tree
#
#    Copyright:: (c) 2024 Darren Kirby
#    Author:: Darren Kirby (mailto:bulliver@gmail.com)

#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import sys
import os

if os.path.isdir("/var/builds/scripts"):
    sys.path.insert(0, '/usr/builds/scripts')
elif os.path.isdir(os.path.expanduser("~/builds/scripts")):
    sys.path.insert(0, os.path.expanduser("~/builds/scripts"))

import builds
import common_functions as cf

try:
    builds.do_main()
except KeyboardInterrupt:
    print()
    cf.red("keyboard interupt received...")
    cf.red("temporary build files possibly left on filesystem")
    sys.exit(-1)

